
dist: trusty
language: php

php:
  - 5.6
  - hhvm
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-dist

script:
  - composer test

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly